apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pod-cleaner-chart.fullname" . }}
  labels:
    {{- include "pod-cleaner-chart.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces", "events"]
  verbs: ["get", "list", "delete", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]